### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by lindhe** [drone/charts#116]
I see that the app version used by this chart is lagging behind [the releases of harness/drone](https://github.com/harness/drone/releases) by a year. Should this chart be considered deprecated/archived?

If so, please clarify that in the README and perhaps mark the repo as archived in GitHub.

If not, please update the chart. 😄 

I was going to ask on Slack, but that's apparently locked down to Harness employees only.

**Comment by jimsheldon** [comment]
I don't maintain a Drone instance these days, so unfortunately this project isn't on my radar as much as it used to be.

Pull requests are always welcome of course 😃 

#117 has the latest Drone server
