### ISSUE TITLE
securityContext example misleading / port 80 hardcoded

### ISSUE THREAD

**Issue by abh** [drone/charts#12]
the `securityContext` section in the default values.yaml implies that dropping all capabilities and running as non-root is possible; however this quickly fails because the chart seemingly is hardcoded to have drone listen on port 80.

**Comment by jimsheldon** [comment]
Apologies for the delay on this. Let's continue the discussion on this in #37

**Comment by abh** [comment]
Thank you for picking it up, @jimsheldon  :-)
