### ISSUE TITLE
Can't deploy drone helm chart on EKS

### ISSUE THREAD

**Issue by gulshenjumayeva** [drone/charts#120]
I've configured drone helm chart and when deploy it, right away fails

No clear error output, why it's failing. 
Error logs:
```
{"level":"fatal","msg":"main: source code management system not configured","time":"2024-02-21T19:53:09Z"}
```

What am I missing any suggestions?

**Comment by bradrydzewski** [comment]
based on that error message, it looks like you need to configure github/gitlab/etc
https://docs.drone.io/server/provider/github/#configuration
https://github.com/drone/charts/blob/master/charts/drone/docs/install.md
