### ISSUE TITLE
How to run drone/drone-admit-members with Helm?

### ISSUE THREAD

**Issue by max-rocket-internet** [drone/charts#15]
It would be good to have either this component optionally included in the main drone chart or have it as a separate chart. I can make a PR? Which would you prefer?

**Comment by tboerger** [comment]
Since not many people use the so far I think a separate chat would be better to keep the amount of options smaller

**Comment by ashwilliams1** [comment]
we only have charts for the runner, server and kubernetes secret manager. We would accept pull requests for additional utilities (such as drone-admin-members, drone-vault, etc)
