### ISSUE TITLE
Running the drone-runner as a daemonset

### ISSUE THREAD

**Issue by krishamoud** [drone/charts#16]
Hello!  Drone is great and these helm charts are incredibly useful.  This is a question, not an issue.

I changed the drone-runner helm chart from a `Deployment` to a `DaemonSet` and I was wondering if there were any downsides of doing this?  

Due to the number of resources I need for my pipelines, our cluster autoscaler is busy and nodes are always coming up and going down.

This sticks out in the docs to me
> The Kubernetes runner must not be restarted while pipelines are running. If you stop or restart the runner while a pipeline is running, it will be stuck in a running state, and the associated Pod must be manually removed.

I wanted to try a DaemonSet in the hopes that there are always enough runners available and that they wont get rescheduled with all of the autoscaling happening.

So far the only issue I've encountered has been needing to refresh a few times to get the drone-runner UI to load.  

Aside from that, are there any gotchas I should be aware of with this approach?

**Comment by jimsheldon** [comment]
Sorry for the delay here.

drone-runner-kube has been deprecated, the drone-runner-docker chart is now the recommended solution for a runner on kubernetes.

Running the docker runner as a DaemonSet sounds reasonable. Drone pipelines will still hang if a runner executing a pipeline is killed by your cluster.
