### ISSUE TITLE
how to pull image from the private docker-registry 

### ISSUE THREAD

**Issue by yizhishang** [drone/charts#19]
the error log like this:   
```
level=warning msg="registry: plugin: cannot get credentials" error="unexpected end of JSON input"
```

and I have set the environments like this 

DRONE_REGISTRY_SKIP_VERIFY | true
-- | --
DRONE_REGISTRY_SECRET | admin:$apr1$rH4GFf2e$9wW1bxtvd8GaZCDIfyLPK/
DRONE_REGISTRY_ENDPOINT | https://docker-registry.yizhishang.com

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
