### ISSUE TITLE
Missing provider specific configuration

### ISSUE THREAD

**Issue by shmileee** [drone/charts#23]
Currently, server chart is too generic and does not support provider specific configurations. Things like [**DRONE_STASH_PRIVATE_KEY**](https://docs.drone.io/server/reference/drone-stash-private-key/) have to be created beforehand and mounted separately. 

Perhaps such values could be supplied during installation step. Prior to submitting PR would love to know what are your  suggestions regarding chart structure.

**Comment by bradrydzewski** [comment]
> server chart is too generic and does not support provider specific configuration

providers are added to the chart as shown here:
https://github.com/drone/charts/blob/master/charts/drone/values.yaml#L194

**Comment by shmileee** [comment]
@bradrydzewski, `DRONE_STASH_PRIVATE_KEY` must contain path to private key inside container, but the file itself has to be created outside of the helm chart installation step and mounted separately. Would it make sense to supply such key as a secret/configmap and let chart handle this on its own?
