### ISSUE TITLE
Project settings

### ISSUE THREAD

**Issue by taorzhang** [drone/charts#26]
how to enable Project settings Trusted 
![image](https://user-images.githubusercontent.com/17560081/100335117-935e3700-300f-11eb-8184-17e0f6cf33bb.png)

**Comment by jimsheldon** [comment]
Apologies for the delay on this.

I don't believe this is related to the Drone helm chart, the 'trusted' setting is per repository, and your user must have admin access to that repository.

Feel free to ask for help with this in [community.harness.io](https://community.harness.io/c/drone/14)
