### ISSUE TITLE
Master chart 1.1.5 while published chart is 1.1.3

### ISSUE THREAD

**Issue by jonathan-mothership** [drone/charts#3]
First off, loving Drone and I like that you've taken ownership of maintaining a repo to properly deploy Drone to Kubernetes, with all the bells and whistles. 

I found an issue trying to migrate from community charts to this one. When I went to deploy it to a sandbox to test out values, helm was unable to find the version of the chart pointed to by the `master` branch, `1.1.5`. When reading the published chart repo index, I see the only chart version published for the `drone` server chart is `1.1.3`. 

Has the CI publish job not run?

**Comment by bradrydzewski** [comment]
thanks, this should be fixed now.  Let me know if you are still seeing issues and we can re-open and triage further.
