### ISSUE TITLE
artifacthub.io metadata

### ISSUE THREAD

**Issue by viceice** [drone/charts#30]
Move the chart repo on artifact.io to `drone` org.

I've invited @gtaylor to the newly created org. He can remove me after accepting.

After this some repo metadata should be added. see https://artifacthub.io/docs/topics/repositories/#helm-charts-repositories

I'm happy to send a pr.

- https://artifacthub.io/packages/helm/drone/drone
- https://artifacthub.io/docs/topics/repositories/#ownership-claim
- https://artifacthub.io/docs/topics/repositories/#official-status

**Comment by jimsheldon** [comment]
Hello @viceice, thank you for suggesting this.

What advantage(s) will artifact.io give the community over the current https://charts.drone.io?

**Comment by viceice** [comment]
You would have a nice web page for viewing possible config options for the chart.

checkout https://artifacthub.io/packages/helm/community-charts/drone

So it's not moving, instead that's a search index and this chart should be registred there to have more visibillity. Will update issue description.

**Comment by jimsheldon** [comment]
Got it, I agree this would be a nice improvement for drone helm users.

@gtaylor is not involved with this project these days, could you invite me instead?

Also, feel free to submit a PR.

Thanks!

**Comment by viceice** [comment]
@jimsheldon Invited you using your github username.

**Comment by jimsheldon** [comment]
Thanks for working on this.

I merged the PR, but I think there is more to be done based on https://artifacthub.io/docs/topics/repositories/#helm-charts-repositories

> There is an extra metadata file that you can add at the repository URL’s path named [artifacthub-repo.yml](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml), which can be used to setup features like [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) or [Ownership claim](https://artifacthub.io/docs/topics/repositories/#ownership-claim). Please note that the artifacthub-repo.yml metadata file must be located at the same level of the chart repository index.yaml file, and it must be served from the chart repository HTTP server as well.

This might mean artifacthub-repo.yml just needs to move under the `docs` directory, I will research more when I have time.

**Comment by viceice** [comment]
After we get the verified publisher, we can ask for official status.

https://artifacthub.io/docs/topics/repositories/#official-status

**Comment by jimsheldon** [comment]
I am very confused, the file is now in place https://charts.drone.io/artifacthub-repo.yml

However, when I try to claim ownership of the drone charts, it won't let me select them. I am not sure when I will have time to pick this up again, but I will keep investigating.

**Comment by jimsheldon** [comment]
On second thought, perhaps this means the repo is claimed successfully? Does that mean #67 can be merged?

**Comment by viceice** [comment]
yes, i already claimed it

**Comment by viceice** [comment]
![image](https://user-images.githubusercontent.com/1798109/170064635-70a2ab7f-335e-4d76-95e7-6b1e639d4b01.png)
🎉 

Now getting `official` status?

**Comment by jimsheldon** [comment]
Making progress! Looks like each chart needs a README, I will work on that, then submit for official status.

**Comment by jimsheldon** [comment]
Adding README in PR #74, which does not address #68, I will submit another PR for all charts for that.

**Comment by viceice** [comment]
thank you 🤗
