### ISSUE TITLE
DRONE_GITEA_SERVER is missing in value.yml

### ISSUE THREAD

**Issue by SvenC56** [drone/charts#4]
Hey,

the `DRONE_GITEA_SERVER` key is missing in the `value.yml` of the drone chart. After inserting it I can connect to the Gitea Server normally. It's just a documentation thing.

Thank you.

**Comment by bradrydzewski** [comment]
@SvenC56 because there are over 100+ configuration parameters we want the canonical documentation to live at docs.drone.io, as opposed to mirroring all of these parameters in the value.yml.

I am open to suggestions to making this more clear in the chart README.  cc @gtaylor

**Comment by bradrydzewski** [comment]
edit:  it looks like we have a subset of parameters for each integration that are commented out, so you are correct that we should have gitea server. I added the value. Thanks!

**Comment by SvenC56** [comment]
Thank you. It was just a minor documentation thing. Like said code works flawlessly.  🙂
