### ISSUE TITLE
clone takes 3 mins

### ISSUE THREAD

**Issue by loeffel-io** [drone/charts#73]
Sometimes the clone plugin takes 3 mins (drone-runner-kube). Is there anything i can debug? 

<img width="374" alt="Bildschirmfoto 2022-06-02 um 19 08 05" src="https://user-images.githubusercontent.com/12670730/171685628-68ffda27-245a-4b34-bc64-b52c666de63d.png">

**Comment by bradrydzewski** [comment]
hey there, this issue tracker is for reporting problems with our Helm chart.  For end-user support questions regarding Drone, please create a thread in our community for at https://community.harness.io/c/drone/14

**Comment by loeffel-io** [comment]
The problem here is that the runner-kube takes way to long to create the pod (GKE); So this really could relate to this repo
