### ISSUE TITLE
Helm charts hard-coded to use HTTP

### ISSUE THREAD

**Issue by danieldsj** [drone/charts#8]
#### USE CASE
My use case is to setup a CICD solution in my homelab for a private repository hosted on Github.  When activating a repository, a Github Webhook is created that attempts to preforms an HTTP post operation against my hostname against the /hook path. 

#### PROBLEM
The charts are hard-coded to use the HTTP port instead of HTTPS which is explicitly discouraged by Github for webhooks.  Examples of this can be found in the deployment, service, and ingress templates:
https://github.com/drone/charts/blob/cfb5b85b5e29ef507651a96b732e1b48e05a5981/charts/drone/templates/deployment.yaml#L38-L41
https://github.com/drone/charts/blob/cfb5b85b5e29ef507651a96b732e1b48e05a5981/charts/drone/templates/service.yaml#L10-L13
https://github.com/drone/charts/blob/cfb5b85b5e29ef507651a96b732e1b48e05a5981/charts/drone/templates/ingress.yaml#L31-L39

Because the chart is hard coded for HTTP, it prevents from using other features like DRONE_TLS_AUTOCERT or manually providing TLS certificates to align with Github best practices.

**Comment by bradrydzewski** [comment]
I don't think this is correct ...  if you want your hooks to use https you need to set `DRONE_SERVER_PROTO=https`

**Comment by bradrydzewski** [comment]
cc @gtaylor could you chime in on https?

**Comment by gtaylor** [comment]
It'd be difficult to support https by default at the Drone server pod level out of the box due to differences in environments. 

The suggested way to do this with less complexity is to use the included Ingress resource: https://github.com/drone/charts/blob/master/charts/drone/templates/ingress.yaml

You can then hook up cert-manager or whatever other cert management tooling you might want.

**Comment by danieldsj** [comment]
Agreed, I eventually used metallb, ingress-nginx and cert-manager when integrating with GitHub via webhook with some success (still troubleshooting when I have time).  By that time I was less dependent on charts and started leaning more towards manifests.

The current drone.io documentation does not provide much guidance for Kubernetes in general, and mostly assumes it is running using docker when discussion certificates and Let's Encrypt, and hopefully when Kubernetes support improves it can provide more guidance on that front.

In the interim, I'm going to consider this issue closed.  Thanks for all of the guidance.
