### ISSUE TITLE
drone-runner-kube ingress resource does not correctly configure path and pathType

### ISSUE THREAD

**Issue by agrahamlincoln** [drone/charts#87]
[this commit](https://github.com/drone/charts/commit/5b9cee8f984c5c5a37ed2652038a9ba65146d568) correctly added support for configuring pathType in ingress resources, but did not update the ingress spec to configure path correctly, and did not update the values.yaml to reflect the correct way to configure ingress.

Without these fixes, it's impossible to apply the drone-runner-kube helm chart version 0.1.9 with `ingress.enabled` set to true. either the server will reject the ingress resource because it's missing pathType, or the ingress path will be configured with path: map[path:/ pathType:Prefix] which is invalid.

If I attempt to apply the ingress resource with an updated values.yaml (including pathType), the ingress resource attempts to change in the following way:

```
          paths:
-           - path: /
+           - path: map[path:/ pathType:Prefix]
+             pathType: Prefix
```

If I attempt to apply the chart with the current values.yaml (with `path: ["/"]`), the ingress resource validation fails with:

`Error: Failed to render chart: exit status 1: Error: template: drone-runner-kube/templates/ingress.yaml:46:23: executing "drone-runner-kube/templates/ingress.yaml" at <.pathType>: can't evaluate field pathType in type interface {}`

**Comment by jimsheldon** [comment]
#86 has been merged, please reopen this if you have any trouble with the new chart
