### ISSUE TITLE
drone images 2.12.1 build using end of life version of alpine 3.11.13 

### ISSUE THREAD

**Issue by sajithvasu** [drone/charts#92]
Drone chart deploys image 2.12.1 and that is build using end of life version of alpine. Please check - https://endoflife.date/alpine

**Comment by bradrydzewski** [comment]
We should really move to using `scratch` for Drone images.  Drone is a static binary with zero external dependencies, which means it does not actually use anything inside the `alpine` base image. Having to upgrade base images across hundreds of repositories (when you consider all of our plugins) creates a lot of busy work, which would be eliminated by using `scratch`.

**Comment by sajithvasu** [comment]
@bradrydzewski: Is there any future plan to fix this for the drone images?

**Comment by loeffel-io** [comment]
why we are not using (distroless)[https://github.com/GoogleContainerTools/distroless]?

**Comment by bradrydzewski** [comment]
`distroless` images contain runtime dependencies.  Drone does not have any runtime dependencies, therefore,`scratch` is more appropriate.

**Comment by jimsheldon** [comment]
I will close this out since these charts don't manage the underlying docker images
